#!/bin/bash
## $Id: archive,v 1.105 2017/05/12 12:12:23 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/archive,v $
# $Revision: 1.105 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford. 
# Licensed for public use under the GPL.
# For assistance contact fulford@fulford.net 0709 229 5385
###################################################################
cmd=`basename $0`
syntax="$cmd [[-b]|[-f]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
ver=`echo "$Id: archive,v 1.105 2017/05/12 12:12:23 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
r=0
mysqldump=/usr/bin/mysqldump
dbo=1
fo=1
while [ $# -gt 0 ] ;do
	case $1 in 
		-b) dbo=0;shift;;
		-c) config=$2;shift 2;;
		-d) debug=1;set -x;shift;;
		-f) fo=0;shift;;
		-l) log=:;shift;;
		-t) mode=test;shift;;
		-v) verbose=1;shift;;
		-V) echo "$cmd $ver";exit;;
		-z) zip=y;shift;;
		 *) host_id=$1;shift ;;
	esac
done
[ $dbo -eq 0  -a $fo -eq 0 ]&&{
	echo "$cmd: cannot combine -f and -b" >&2
	exit
}
config=${config:-"/usr/local/etc/archive.cf"}
[ -z "$host_id" ]&&{ echo "$cmd: host_id required" >&2 ;exit 1 ;}
tmp=/tmp/$cmd-$$
exclude=`echo $exclude|sed -e 's/[,;:]/\|/g;s/\//\\\/g'`
dbtmp=/tmp/$cmd-db$$
verbose=${verbose:-0}
[ "$log" ] && logger -t archive: "$cmd on $host_id started"
if [ -r $config ];then
	grep -q $host_id $config ||{
		echo "$cmd: $host_id not found in $config">&2
		exit 1
	}
	sed -ne '/^'$host_id':/,/^$/{
		/^[	 ]db:.*/d 
		/^[	 ].*/p
	}' $config >$tmp
	. $tmp
	[ $verbose -eq 1 ] && cat $tmp
	sed -ne '/^'$host_id':/,/^$/p' $config|
		awk -F: '/^[ \t]db:/{print $2}' >$dbtmp
else
	echo "$cmd: Can't read $config" >&2
	exit 1
fi
ftphost=${ftphost:-$host}
[ $host != `hostname -f` ] && { remote="ssh $host";bs="bs=8192" ;}

_end () {
	if [ "$r" -lt 1 ];then
		rm $tmp
		[ -f $dbtmp ] && rm $dbtmp
		[ "$log" ] && logger -t archive: "$cmd on $host finished"
	else
		[ "$log" ] && logger -t archive: "$cmd on $host failed"
		echo "$cmd on $host failed" >&2
	fi

}

[ -z "$dest" ] &&{ echo "$cmd: no tape device specified for $host">&2;exit 1;}
sudo [ -e "$dest" ] ||{ echo "$cmd: $dest does not exist">&2;exit 1;}
[ -z "$backup" ] &&{
	echo "$cmd: no backup command specified for $host">&2;exit 1
}

if sudo [ ! -w $dest ];then
	echo "$backup: Can't write to $dest">&2 ;_end
fi
# backup databases unless $fo (files only) set
[ $fo -ne 0 ] &&{
cat $dbtmp|
while read line;do
	db=`echo $line|awk -F'=' '{printf $1}'`
	pass=`echo $line|awk -F= '{printf $2}'`
	archive=$dest/`date +%y%m%d`$db.sql
	[ "$verbose" -eq 1 ] &&{
	     echo "sudo $mysqldump -h $host --databases $db |dd of=$archive"
	}
#	[ "$verbose" -eq 0 ]&&{
#		sudo $mysqldump -h $host  $db|sudo dd of=$archive 2>/dev/null
#	}
	sudo $mysqldump -h $host  $db $redirect |sudo dd of=$archive
	#sudo mysqldump -h $host  $db $redirect |sudo dd of=$archive
	r=$?
done
}

#backup files unless dbo=true (database only)
[ $dbo -ne 0 ] &&{
  method=`echo $backup|awk '{print $1}'`
  case $method in	
  	tar) $remote df -l|awk 'NR > 1{if($1 !~ /tmpfs/ && $1 !~ /loop/ && $1 !~ /sr0/ ) print $6}'>$tmp
		n=`cat $tmp|wc -l` 
		c=0
		while [ $c -le $n ];do
			c=`expr $c + 1`
			fss="$fss `awk <$tmp -v c=$c 'NR == c{print}'`"
		done
		for fs in $fss ;do
		   fn=`basename $fs`
		   [ $fn = "/" ] && fn=root
		   archive=`date +%u`.${fn}.tar
		   [ $verbose -eq 1 ] && {
			echo -n "$cmd: file system $fn to $archive: "
		    }
		   [ "$mode" = "test" ] &&{ echo=echo ;}
		   if [ -n "$remote" ];then 
		       $remote "sudo $backup - $fs 2>/dev/null|gzip -c|dd bs=8192"|
		       sudo dd status=none of=$dest/$archive.gz
		   else
		  	if [ "$zip" = "y" ];then 
				sudo $backup - $fs 2>/dev/null|sudo gzip|
				sudo dd of=$dest/$archive.gz 2>/dev/null
				r=$?
			else
				sudo $backup - $fs 2>/dev/null|
					dd of=$dest/$archive 2>/dev/null
					r=$?
			fi
		    fi
	            if [ $r -eq 0 ]; then
			result="complete"
		    else 
			result="failed"
		    fi
		    [ "$log" ] && {
			logger -t $cmd: "file system $fn to $archive - $result."
		    }
		    [ $verbose -eq 1 ] && {
			echo $result 
		    }
		done
		;;
	 lftp)
		[ $verbose -gt 0 ] && {
		    echo -n "$cmd using $backup to mirror $host to $dest: " >&2
		}
		$backup -u $user,$pass $ftphost -e "mirror --only-newer $src $dest;quit"	
		r=$?
	        if [ $r -eq 0 ]; then
			result="complete."
		else 
			result="failed."
		fi
		[ "$log" ] && {
			logger -t $cmd: "file system $fn to $archive - $result"
		}
		[ $verbose -eq 1 ] && {
			echo $result >&2
		}
		;;
	esac
}
_end
