#!/bin/bash
## $Id: archive,v 1.131 2017/07/11 09:18:00 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/archive,v $
# $Revision: 1.131 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford. 
# Licensed for public use under the GPL.
# For assistance contact fulford@fulford.net 0709 229 5385
###################################################################
cmd=`basename $0`
syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
ver=`echo "$Id: archive,v 1.131 2017/07/11 09:18:00 fulford Exp $"|awk '{print $3,$4,$5}'`
r=0
mysqldump=/usr/bin/mysqldump
dbo=1
fo=1
rso=1
status="status=none"
while [ $# -gt 0 ] ;do
	case $1 in 
		-b) dbo=0;shift;;
		-c) config=$2;shift 2;;
		-d) debug=1;set -x;unset status;shift;;
		-f) fo=0;shift;;
		-l) log=:;shift;;
		-r) rso=0;shift;; 
		-t) mode=test;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $ver";exit;;
		-z) zip=y;shift;;
		 *) host_id=$1;shift ;;
	esac
done
[ $dbo -eq 0  -a $fo -eq 0 -o $rso -eq 0 ]&&{
	echo "$cmd: only one of -f, -b  or -r allowed." >&2
	exit
}
config=${config:-"/usr/local/etc/archive.cf"}
[ -z "$host_id" ]&&{ echo "$cmd: host_id required" >&2 ;exit 1 ;}
tmp=/tmp/$cmd-$$
exclude=`echo $exclude|sed -e 's/[,;:]/\|/g;s/\//\\\/g'`
dbtmp=/tmp/$cmd-db$$
[ "$log" ] && logger -t archive: "$cmd on $host_id started"
if [ -r $config ];then
	grep -q $host_id $config ||{
		echo "$cmd: $host_id not found in $config">&2
		exit 1
	}
	sed -ne '/^'$host_id':/,/^$/{
		/^[	 ]db:.*/d 
		/^[	 ].*/p
	}' $config >$tmp
	. $tmp
	[ $verbose ] && cat $tmp
	sed -ne '/^'$host_id':/,/^$/p' $config|
		awk -F: '/^[ \t]db:/{print $2}' >$dbtmp
else
	echo "$cmd: Can't read $config" >&2
	exit 1
fi
ftphost=${ftphost:-$host}
[ $host != `hostname -f` ] && { remote="ssh -y $host";bs="bs=8192" ;}

_end () {
	if [ "$r" -lt 1 ];then
		rm $tmp
		[ -f $dbtmp ] && rm $dbtmp
		[ "$log" ] && logger -t archive: "$cmd on $host finished"
	else
		[ "$log" ] && logger -t archive: "$cmd on $host failed"
		echo "$cmd on $host failed" >&2
	fi

}

[ -z "$dest" ] &&{ echo "$cmd: no tape device specified for $host">&2;exit 1;}
sudo [ -e "$dest" ] ||{ echo "$cmd: $dest does not exist">&2;exit 1;}
[ -z "$backup" ] &&{
	echo "$cmd: no backup command specified for $host">&2;exit 1
}

if sudo [ ! -w $dest ];then
	echo "$backup: Can't write to $dest">&2 ;_end
fi
# backup databases unless $fo (files only) set
[ $fo -ne 0 -a $rso -ne 0 ] &&{
cat $dbtmp|
while read line;do
	db=`echo $line|awk -F'=' '{printf $1}'`
	pass=`echo $line|awk -F= '{printf $2}'`
	if [ $pass ] ;then 
		user=$db
		pass="-p$pass"
	else
		user=root
		pass=""
	fi
	archive=$dest/$db.`date +%u`.sql
	[ $verbose ] &&{
	     echo "sudo $mysqldump -h $host -u $user $pass --databases $db|">&2
	     echo "dd $status of=$archive">&2
	}
	sudo $mysqldump -h $host -u $user $pass $db|sudo dd $status of=$archive
	r=$?
done
}

# carry out rsync unless dbo true (database only) or fo true (file backup only).
[ $dbo -ne 0 -a $fo -ne 0 ] &&{
	# check for rsync
	if [ -n "$rsync" ] ;then
		[ "$root_usr" = y ] && {
			sudo="sudo"
		}
		[ $verbose ] && {
			echo "$cmd: starting rsync on $host" >&2
		}
		lmsg="$cmd $rsync "
		result=`ssh -y $host "$sudo rsync $rsync && echo complete || echo failed"`
		[ $verbose ] && {
			echo "$cmd: rsync on $host $result" >&2
		} 
		[ $log ] && {
			logger -t $cmd "rsync on $host $result"
		}
	fi
}

#backup files unless dbo=true (database only) or rso=true (rsync only)
[ $dbo -ne 0 -a $rso -ne 0 ] &&{
  method=`echo $backup|awk '{print $1}'`
  case $method in	
  	tar) if [ -n "$fss" ] ;then
		$remote df -l|
		awk 'NR > 1{
		 if($1 !~ /tmpfs/ && $1 !~ /loop/ && $1 !~ /sr0/)print $6}'>$tmp
		n=`cat $tmp|wc -l` 
		c=0
		while [ $c -le $n ];do
			c=`expr $c + 1`
			fss="$fss `awk <$tmp -v c=$c 'NR == c{print}'`"
		done
	      fi
	      for fs in $fss ;do
	   	fn=`basename $fs`
		[ $fn = "/" ] && fn=root
		archive=`date +%u`.${fn}.tar.gz
		[ "$zip" ] && archive=${archive}.gz
		[ $verbose ] && {
			echo -n "$cmd: file system $fn on $host to $archive: "
		}
		[ "$mode" = "test" ] &&{ echo=echo ;}
		if [ -n "$remote" ];then 
			$remote "sudo $backup - $fs 2>/dev/null|gzip -c|
			dd $status bs=8192"|
			sudo dd $status of=$dest/$archive
		else
			if [ "$zip" = "y" ];then 
				sudo $backup - $fs 2>/dev/null|sudo gzip|
				sudo dd $status of=$dest/$archive 2>/dev/null
				r=$?
			else
				sudo $backup - $fs 2>/dev/null|
				sudo dd $status of=$dest/$archive 2>/dev/null
				r=$?
			fi
		 fi
	            	if [ $r -eq 0 ]; then
				result="complete"
		    	else 
				result="failed"
		    	fi
		    	[ "$log" ] && {
			logger -t $cmd: "$fn on $host to $archive - $result."
		    	}
		    	[ $verbose ] && {
				echo $result 
		    	}
		done
		;;
	 lftp)
		[ $verbose ] && {
		    echo -n "$cmd using $backup to mirror $host to $dest: " >&2
		}
		$backup -u $user,$pass $ftphost -e "mirror --only-newer $src $dest;quit"	
		r=$?
	        if [ $r -eq 0 ]; then
			result="complete."
		else 
			result="failed."
		fi
		[ "$log" ] && {
			logger -t $cmd: "file system $fn to $archive - $result"
		}
		[ $verbose ] && {
			echo $result >&2
		}
		;;
	esac
}
_end
